{% set name = "tramway" %}
{% set version = "0.6.9" %}
{% set python_min = "3.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/TRamWAy/archive/v{{ version }}.tar.gz
  sha256: 420bacf86c55ad740e3d0348092e064c7797bbde749ac00ddc99a910131060a8

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - hdf5
    - python >={{ python_min }}
    - rwa-python =0.9.5
    - matplotlib-base
    - cvxopt
    - polytope
    - tqdm
    - scikit-image
    - setuptools

test:
  imports:
    - tramway
  source_files:
    - tests/test_core.py
    - tests/test_analyzer.py
    - tests/test_analyzer_pipeline.py
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest tests/test_core.py tests/test_analyzer.py::TestSptDataAccess tests/test_analyzer.py::TestTesseller tests/test_analyzer.py::TestIndexer tests/test_analyzer.py::TestAssignment tests/test_analyzer.py::TestSideEffects

about:
  home: https://github.com/DecBayComp/TRamWAy
  license: CECILL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'The RAndom Walk AnalYzer: analysis toolbox for localization microscopy data'
  doc_url: https://tramway.readthedocs.io/

extra:
  recipe-maintainers:
    - francoislaurent
    - DecBayComp
